
INSERT INTO cms_articles_2026_05_29
  (slug, title, subtitle, summary, content, image_url, source, source_url, topic, tags, edition_date, news_date, is_highlight)
VALUES

-- ── 25/05 ─────────────────────────────────────────────────────────────────────
(
  'cnpe-etanol-mistura-gasolina-junho-2026',
  'CNPE deve discutir aumento da mistura de etanol na gasolina em junho',
  'Governo avalia elevar percentual de etanol anidro de 30% para 32%',
  'O Conselho Nacional de Política Energética (CNPE) deve pautar, em junho, a discussão sobre o aumento da mistura obrigatória de etanol anidro na gasolina. A proposta em análise prevê elevar o percentual de 30% para 32%, o que representaria um incremento significativo na demanda pelo biocombustível e impacto direto na cadeia sucroenergética nacional.',
  '<p>O Conselho Nacional de Política Energética (CNPE) deve pautar, em junho, a discussão sobre o aumento da mistura obrigatória de etanol anidro na gasolina. A proposta em análise prevê elevar o percentual de 30% para 32%.</p><p>A medida, se aprovada, representaria um incremento expressivo na demanda pelo biocombustível produzido principalmente no Brasil, que é o segundo maior produtor mundial de etanol. A iniciativa está alinhada à política do Governo Federal de ampliar o uso de biocombustíveis como estratégia de descarbonização e contenção da inflação de combustíveis.</p><p>Segundo fontes do setor, a proposta conta com apoio da indústria sucroenergética e de associações como a UNICA (União da Indústria de Cana-de-Açúcar e Bioenergia). O aumento da mistura beneficiaria especialmente os produtores de cana-de-açúcar das regiões Centro-Sul e Nordeste.</p>',
  'https://images.unsplash.com/photo-1586315776885-a176ffccbe01?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/sugar-etanol/2/1135738/cnpe-deve-discutir-aumento-da-mistura-de-etanol-na-gasolina-em-junho',
  'Biocombustíveis',
  ARRAY['etanol','gasolina','CNPE','energia renovável','cana-de-açúcar'],
  '2026-05-29', '2026-05-25', true
),
(
  'colheita-segunda-safra-milho-mato-grosso-2026',
  'Colheita da segunda safra de milho tem início no Mato Grosso',
  'Imea projeta uma produção de 52,65 milhões de toneladas',
  'A colheita da segunda safra de milho (milho safrinha) teve início no estado do Mato Grosso, maior produtor nacional. O Instituto Mato-Grossense de Economia Agropecuária (Imea) projeta uma produção total de 52,65 milhões de toneladas, número que consolida o protagonismo do estado no abastecimento interno e nas exportações de milho.',
  '<p>A colheita da segunda safra de milho (milho safrinha) teve início no estado do Mato Grosso, maior produtor nacional. O Instituto Mato-Grossense de Economia Agropecuária (Imea) projeta uma produção total de 52,65 milhões de toneladas.</p><p>As primeiras colhedoras entraram nas lavouras em condições favoráveis, com umidade dos grãos dentro dos padrões ideais. Analistas do setor destacam que o resultado final dependerá das condições climáticas nas próximas semanas, especialmente no sul do estado.</p><p>O milho safrinha representa cerca de 75% de toda a produção nacional de milho e tem papel fundamental na competitividade do agronegócio brasileiro, especialmente no segmento de proteína animal (suínos e aves).</p>',
  'https://images.unsplash.com/photo-1601593346740-925612772716?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/corn/9/1135374/colheita-da-segunda-safra-de-milho-tem-inicio-no-mato-grosso',
  'Grãos',
  ARRAY['milho','safrinha','Mato Grosso','Imea','colheita'],
  '2026-05-29', '2026-05-25', true
),
(
  'abiec-embargo-chines-frigorifico-preventivo-temporario',
  'Abiec diz que embargo chinês a três frigoríficos tem caráter preventivo e temporário',
  'Brasil possui um dos sistemas de controle sanitário mais rigorosos do mundo',
  'A Associação Brasileira das Indústrias Exportadoras de Carnes (Abiec) classificou como preventiva e temporária a suspensão de habilitações de três plantas frigoríficas brasileiras pela China. A entidade reforçou que o Brasil mantém um dos sistemas de controle sanitário mais rigorosos do mundo, com monitoramento permanente da cadeia produtiva e fiscalização do Serviço de Inspeção Federal (SIF).',
  '<p>A Associação Brasileira das Indústrias Exportadoras de Carnes (Abiec) classificou como preventiva e temporária a suspensão de habilitações de três plantas frigoríficas brasileiras imposta pela China.</p><p>Em nota, a entidade reforçou que o Brasil mantém um dos sistemas de controle sanitário mais rigorosos do mundo, com monitoramento permanente da cadeia produtiva e fiscalização do Serviço de Inspeção Federal (SIF). A Abiec afirmou que as plantas afetadas já tomaram as medidas necessárias para atender às exigências do mercado chinês.</p><p>A China é o principal destino das exportações de carne bovina brasileira, respondendo por cerca de 40% do total exportado. O embargo, mesmo que temporário, gera atenção no mercado, mas a Abiec garantiu que o fluxo geral de exportações não foi comprometido.</p>',
  'https://images.unsplash.com/photo-1559707576-d8806b4a56a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/livestock/5/1135450/abiec-diz-que-embargo-chines-a-tres-plantas-de-frigorificos-tem-carater-preventivo-e-temporario',
  'Pecuária',
  ARRAY['carne bovina','China','exportação','Abiec','frigoríficos'],
  '2026-05-29', '2026-05-25', true
),
(
  'agroindustria-cresce-04-primeiro-trimestre-2026',
  'Agroindústria cresce 0,4% no primeiro trimestre de 2026',
  'Desempenho positivo foi fundamental para evitar campo negativo na Indústria de Transformação',
  'Segundo a FGVAgro, a agroindústria registrou crescimento de 0,4% no primeiro trimestre de 2026. O desempenho positivo do segmento foi fundamental para que a Indústria de Transformação como um todo não operasse em campo negativo no mesmo período, evidenciando o papel estratégico do agronegócio na sustentação da atividade industrial brasileira.',
  '<p>Segundo a FGVAgro, a agroindústria registrou crescimento de 0,4% no primeiro trimestre de 2026. O desempenho positivo do segmento foi fundamental para que a Indústria de Transformação como um todo não operasse em campo negativo no mesmo período.</p><p>O resultado reforça a relevância do agronegócio como pilar da economia brasileira, mesmo em um cenário de juros elevados e câmbio volátil. As empresas processadoras de grãos, carnes e derivados de cana-de-açúcar foram os principais responsáveis pelo resultado positivo.</p><p>A FGVAgro destacou que a tendência de crescimento deve se manter ao longo do segundo trimestre, impulsionada pela safra recorde de soja e pela expectativa de boa colheita de milho safrinha.</p>',
  'https://images.unsplash.com/photo-1616261167032-b16d2df8333b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1135605/agroindustria-cresce-04-no-primeiro-trimestre',
  'Agroeconomia',
  ARRAY['agroindústria','PIB','FGVAgro','crescimento','economia'],
  '2026-05-29', '2026-05-25', false
),
(
  'uso-calcario-corretivo-solo-cresce-28-dois-anos',
  'Uso de calcário como corretivo do solo cresce apenas 2,8% nos últimos dois anos',
  'Brasil mantém níveis de aplicação de corretivos em patamares preocupantes, alerta Abracal',
  'O Brasil mantém níveis de aplicação de calcário como corretivo do solo em patamares preocupantes de defasagem, segundo alerta da Abracal (Associação Brasileira dos Produtores de Calcário Agrícola). Nos últimos dois anos, o crescimento no uso do insumo foi de apenas 2,8%, muito abaixo do necessário para corrigir a acidez dos solos tropicais brasileiros e garantir máxima produtividade.',
  '<p>O Brasil mantém níveis de aplicação de calcário como corretivo do solo em patamares preocupantes de defasagem, segundo alerta da Abracal. Nos últimos dois anos, o crescimento no uso do insumo foi de apenas 2,8%.</p><p>Especialistas alertam que a acidez do solo é um dos principais limitadores de produtividade na agricultura tropical. Estima-se que cerca de 50% dos solos agricultáveis do Brasil necessitam de correção, mas o ritmo atual de aplicação está muito aquém do ideal.</p><p>A Abracal recomenda que produtores realizem análises de solo regularmente e adotem programas de calagem para elevar o pH e disponibilizar nutrientes para as plantas, o que pode aumentar a produtividade em até 30% em algumas culturas.</p>',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1135473/uso-de-calcario-como-corretivo-do-solo-cresce-apenas-28-nos-ultimos-dois-anos',
  'Insumos',
  ARRAY['calcário','solo','corretivo','produtividade','Abracal'],
  '2026-05-29', '2026-05-25', false
),
(
  'governo-negocia-revisao-cota-exportacao-carne-bovina-china',
  'Governo negocia revisão da cota de exportação de carne bovina para a China',
  'China mantém cota anual de 1,1 milhão de toneladas para importação da proteína brasileira',
  'O Governo Federal está em negociação com a China para revisar a cota de exportação de carne bovina brasileira. Atualmente, o gigante asiático mantém uma cota anual de 1,1 milhão de toneladas para importação da proteína brasileira. A revisão para cima é vista pelo setor como fundamental para ampliar o acesso ao maior mercado importador de carne do mundo.',
  '<p>O Governo Federal está em negociação com a China para revisar a cota de exportação de carne bovina brasileira. Atualmente, o gigante asiático mantém uma cota anual de 1,1 milhão de toneladas para importação da proteína brasileira.</p><p>A revisão para cima é vista pelo setor como fundamental para ampliar o acesso ao maior mercado importador de carne do mundo. O Brasil é o maior exportador mundial de carne bovina e a China representa mais de 40% das exportações brasileiras da proteína.</p><p>Ministério da Agricultura e representantes da cadeia produtiva estão alinhados na defesa de uma ampliação da cota, que beneficiaria diretamente pecuaristas e frigoríficos em todo o país.</p>',
  'https://images.unsplash.com/photo-1559707576-d8806b4a56a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/livestock/5/1135879/governo-negocia-revisao-da-cota-de-exportacao-de-carne-bovina-brasileira-para-a-china',
  'Pecuária',
  ARRAY['carne bovina','China','exportação','cota','comércio exterior'],
  '2026-05-29', '2026-05-25', false
),
(
  'metade-produtores-cafe-brasileiros-pequenos-negocios',
  'Mais da metade dos produtores brasileiros de café são pequenos negócios',
  'Levantamento do Sebrae revela concentração fora do Sudeste',
  'Um levantamento do Sebrae revelou que mais da metade dos produtores brasileiros de café são classificados como pequenos negócios. O estudo ainda aponta que os estados fora do Sudeste concentram um número expressivo de pequenos produtores, revelando a capilaridade e a importância social do setor cafeeiro no Brasil, segundo maior produtor e maior exportador mundial de café.',
  '<p>Um levantamento do Sebrae revelou que mais da metade dos produtores brasileiros de café são classificados como pequenos negócios. O estudo ainda aponta que os estados fora do Sudeste concentram um número expressivo de pequenos produtores.</p><p>O Brasil é o maior produtor e exportador mundial de café, com destaque para as variedades arábica e conilon (robusta). A pesquisa evidencia que o setor tem uma base produtiva diversificada, com forte presença de pequenos e médios produtores em estados como Rondônia, Bahia e Minas Gerais.</p><p>O Sebrae destacou que programas de crédito, assistência técnica e acesso a mercados são fundamentais para fortalecer esse segmento e garantir a competitividade do café brasileiro no mercado global.</p>',
  'https://images.unsplash.com/photo-1447933601403-0c6688de566e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/coffee/3/1135846/mais-da-metade-dos-produtores-brasileiros-de-cafe-sao-pequenos-negocios-aponta-pesquisa',
  'Café',
  ARRAY['café','Sebrae','pequenos produtores','cafeicultura','agronegócio'],
  '2026-05-29', '2026-05-25', false
),
(
  'governo-federal-lanca-quinta-rodada-leilao-eco-invest',
  'Governo federal lança a quinta rodada do leilão Eco Invest',
  'Expectativa é arrecadar R$ 50 bilhões para biofertilizantes e biocombustíveis',
  'O Governo Federal lançou a quinta rodada do leilão Eco Invest, com expectativa de arrecadar R$ 50 bilhões para fomentar as indústrias de biofertilizantes e biocombustíveis. A iniciativa faz parte da política de transição energética e de fortalecimento da bioeconomia brasileira, posicionando o país como referência global em produção sustentável.',
  '<p>O Governo Federal lançou a quinta rodada do leilão Eco Invest, com expectativa de arrecadar R$ 50 bilhões para fomentar as indústrias de biofertilizantes e biocombustíveis.</p><p>A iniciativa faz parte da política de transição energética e de fortalecimento da bioeconomia brasileira. Os recursos captados serão direcionados para projetos de produção de biocombustíveis avançados e biofertilizantes, com foco em sustentabilidade e redução de emissões de gases de efeito estufa.</p><p>O leilão Eco Invest tem atraído interesse de grandes players nacionais e internacionais do setor energético e agroindustrial, consolidando o Brasil como destino preferencial para investimentos em bioeconomia.</p>',
  'https://images.unsplash.com/photo-1586315776885-a176ffccbe01?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/sugar-etanol/2/1135771/governo-federal-lanca-a-quinta-rodada-do-leilao-eco-invest',
  'Biocombustíveis',
  ARRAY['biocombustíveis','biofertilizantes','Eco Invest','sustentabilidade','investimento'],
  '2026-05-29', '2026-05-25', false
),

-- ── 26/05 ─────────────────────────────────────────────────────────────────────
(
  'colheita-milho-safrinha-parana-deral-2026',
  'Colheita do milho safrinha começa de forma incipiente no Paraná',
  'Chuvas recentes ajudaram na manutenção da umidade dos solos',
  'O Departamento de Economia Rural (Deral) do Paraná informou que a colheita do milho safrinha começou de forma incipiente no estado. Chuvas recentes ajudaram na manutenção da umidade dos solos e favoreceram o desenvolvimento das lavouras, o que traz perspectivas positivas para a safra paranaense.',
  '<p>O Departamento de Economia Rural (Deral) do Paraná informou que a colheita do milho safrinha começou de forma incipiente no estado. Chuvas recentes ajudaram na manutenção da umidade dos solos e favoreceram o desenvolvimento das lavouras.</p><p>O Paraná é o segundo maior produtor de milho safrinha do Brasil, atrás apenas do Mato Grosso. A safra paranaense tem relevância estratégica para o abastecimento interno e para as exportações pelo porto de Paranaguá.</p><p>Técnicos do Deral apontam que a qualidade das lavouras está acima da média, com boa formação de espigas e grãos, o que pode resultar em produtividade superior à temporada anterior.</p>',
  'https://images.unsplash.com/photo-1601593346740-925612772716?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/agricultura/colheita-do-milho-safrinha-comeca-de-forma-incipiente-no-parana-aponta-o-deral',
  'Grãos',
  ARRAY['milho','safrinha','Paraná','Deral','colheita'],
  '2026-05-29', '2026-05-26', false
),
(
  'preco-produtor-leite-rs-queda-mensal-maio-2026',
  'Preço pago ao produtor de leite no RS deve fechar maio com queda de 3,38%',
  'Conseleite projeta litro encerrando o mês em R$ 2,4478',
  'O Conseleite-RS (Conselho Paritário Produtores-Indústrias de Leite do RS) projeta que o preço pago ao produtor de leite no Rio Grande do Sul deve encerrar maio com queda mensal de 3,38%, com o valor do litro chegando a R$ 2,4478. A pressão de queda reflete o ajuste sazonal típico do período e o excesso de oferta em algumas regiões.',
  '<p>O Conseleite-RS projeta que o preço pago ao produtor de leite no Rio Grande do Sul deve encerrar maio com queda mensal de 3,38%, com o valor do litro chegando a R$ 2,4478.</p><p>A pressão de queda reflete o ajuste sazonal típico do período, com aumento da produção em função das condições climáticas favoráveis e do excesso de oferta em algumas regiões.</p><p>Produtores gaúchos estão atentos ao cenário e algumas cooperativas já anteciparam medidas para escoar a produção, incluindo aumento das exportações de leite em pó e queijo. A expectativa é de recuperação dos preços a partir de junho.</p>',
  'https://images.unsplash.com/photo-1550583724-b2692b85b150?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/livestock/5/1137037/preco-pago-ao-produtor-de-leite-no-rs-deve-fechar-maio-com-queda-mensal-de-338',
  'Pecuária',
  ARRAY['leite','preço ao produtor','Rio Grande do Sul','Conseleite','laticínios'],
  '2026-05-29', '2026-05-26', false
),
(
  'ministerio-agricultura-sistema-unificado-registro-defensivos',
  'Ministério da Agricultura lança sistema unificado para registro de defensivos agrícolas',
  'Sispa marca avanço na modernização dos processos regulatórios',
  'O Ministério da Agricultura lançou o Sispa (Sistema Integrado de Solicitação e Acompanhamento de Processos Agrotóxicos), um sistema unificado para registro de defensivos agrícolas. A iniciativa marca um avanço na modernização dos processos regulatórios do setor, com digitalização completa dos pedidos de registro e maior transparência no acompanhamento dos processos.',
  '<p>O Ministério da Agricultura lançou o Sispa, um sistema unificado para registro de defensivos agrícolas. A iniciativa marca um avanço na modernização dos processos regulatórios do setor.</p><p>Com o Sispa, os pedidos de registro de defensivos agrícolas serão processados de forma digital, com maior agilidade e transparência. A estimativa do Ministério é que o tempo médio de análise de um pedido de registro seja reduzido em até 40%.</p><p>O Brasil é o maior mercado mundial de defensivos agrícolas, e a modernização do sistema regulatório é considerada fundamental para aumentar a competitividade do agronegócio e garantir o acesso a produtos mais eficientes e seguros.</p>',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1136962/ministerio-da-agricultura-lanca-sistema-unificado-para-registro-de-defensivos-agricolas',
  'Política Agrícola',
  ARRAY['defensivos agrícolas','Sispa','regulação','Ministério da Agricultura','modernização'],
  '2026-05-29', '2026-05-26', false
),
(
  'municipios-financiamento-assistencia-tecnica-extensao-rural',
  'Municípios respondem por metade do financiamento de assistência técnica rural',
  'De 2016 a 2025, investimento municipal atingiu R$ 26 bilhões',
  'Um estudo da Confederação Nacional de Municípios (CNM) revelou que os municípios brasileiros respondem por praticamente metade do financiamento dedicado à assistência técnica e extensão rural (Ater). De 2016 a 2025, o investimento municipal nesse setor atingiu R$ 26 bilhões, reforçando o papel dos governos locais no suporte ao produtor rural.',
  '<p>Um estudo da Confederação Nacional de Municípios (CNM) revelou que os municípios brasileiros respondem por praticamente metade do financiamento dedicado à assistência técnica e extensão rural (Ater). De 2016 a 2025, o investimento municipal nesse setor atingiu R$ 26 bilhões.</p><p>Os dados reforçam o papel estratégico dos governos locais no suporte ao produtor rural, especialmente para pequenos e médios agricultores que dependem de orientação técnica para aumentar a produtividade e adotar boas práticas agrícolas.</p><p>A CNM recomenda que os municípios fortaleçam suas estruturas de Ater e busquem parcerias com estados e governo federal para ampliar o alcance dos serviços prestados aos produtores rurais.</p>',
  'https://images.unsplash.com/photo-1638403398129-23d6714e8c81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1136714/municipios-respondem-por-praticamente-metade-do-financiamento-dedicado-a-assistencia-tecnica-e-extensao-rural',
  'Política Agrícola',
  ARRAY['assistência técnica','extensão rural','municípios','CNM','investimento'],
  '2026-05-29', '2026-05-26', false
),
(
  'ministerio-agricultura-plano-inova-cacau-2030',
  'Ministério da Agricultura institui Plano Inova Cacau 2030',
  'Iniciativa visa promover desenvolvimento sustentável do segmento',
  'O Ministério da Agricultura instituiu o Plano Inova Cacau 2030, iniciativa que tem como objetivo promover o desenvolvimento sustentável da cadeia produtiva do cacau no Brasil. O plano prevê ações de pesquisa, desenvolvimento tecnológico, acesso a mercados e fortalecimento da cacauicultura brasileira, com foco especial na região Sul da Bahia e no Pará.',
  '<p>O Ministério da Agricultura instituiu o Plano Inova Cacau 2030, iniciativa que tem como objetivo promover o desenvolvimento sustentável da cadeia produtiva do cacau no Brasil.</p><p>O plano prevê ações de pesquisa e desenvolvimento tecnológico, acesso a mercados nacionais e internacionais, e fortalecimento da cacauicultura brasileira. As regiões Sul da Bahia e Pará são o foco principal das ações, por concentrarem a maior parte da produção nacional.</p><p>O Brasil, que já foi o maior produtor mundial de cacau, busca recuperar protagonismo no mercado global com cacau de alta qualidade e produção sustentável. O mercado de chocolates finos tem demanda crescente por cacau brasileiro, especialmente na Europa e Estados Unidos.</p>',
  'https://images.unsplash.com/photo-1511381939415-e44f069e9b3a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/mais-culturas/15/1136690/ministerio-da-agricultura-institui-plano-inova-cacau-2030',
  'Outras Culturas',
  ARRAY['cacau','chocolate','Plano Inova','Ministério da Agricultura','sustentabilidade'],
  '2026-05-29', '2026-05-26', false
),
(
  'cnh-tim-investem-77-milhoes-conectividade-rural',
  'CNH e TIM investem R$ 77 milhões em nova iniciativa de conectividade rural',
  '97 torres devem conectar 1,5 milhão de hectares em Minas Gerais',
  'A CNH Industrial e a TIM anunciaram um investimento conjunto de cerca de R$ 77 milhões em uma nova iniciativa de conectividade rural no Brasil. O projeto prevê a instalação de 97 torres de telecomunicações em Minas Gerais, com previsão de implantação em até 18 meses. A infraestrutura deve conectar aproximadamente 1,5 milhão de hectares de área rural.',
  '<p>A CNH Industrial e a TIM anunciaram um investimento conjunto de cerca de R$ 77 milhões em uma nova iniciativa de conectividade rural. O projeto prevê a instalação de 97 torres de telecomunicações em Minas Gerais.</p><p>Com previsão de implantação em até 18 meses, a infraestrutura deve conectar aproximadamente 1,5 milhão de hectares de área rural, beneficiando produtores que hoje enfrentam dificuldades de comunicação e acesso à tecnologia no campo.</p><p>A conectividade rural é considerada um dos pilares da agricultura de precisão e da digitalização do agronegócio. Com acesso à internet de qualidade, produtores podem monitorar lavouras remotamente, acessar dados climáticos em tempo real e operar máquinas de forma automatizada.</p>',
  'https://images.unsplash.com/photo-1451187580459-43490279c0fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1136571/cnh-e-tim-investem-cerca-de-rdollar-77-milhoes-em-nova-iniciativa-de-conectividade-rural',
  'Tecnologia',
  ARRAY['conectividade','internet rural','CNH','TIM','tecnologia','Minas Gerais'],
  '2026-05-29', '2026-05-26', false
),

-- ── 27/05 ─────────────────────────────────────────────────────────────────────
(
  'moagem-cana-centro-sul-dobra-quinzena-abril-2026',
  'Moagem de cana no Centro-Sul dobra na 2ª quinzena de abril, aponta Unica',
  'Produção de etanol avança mais de 70% no acumulado da safra 2026/27',
  'A moagem de cana-de-açúcar no Centro-Sul do Brasil dobrou na segunda quinzena de abril em comparação ao início da safra, segundo dados da Unica (União da Indústria de Cana-de-Açúcar e Bioenergia). A produção de etanol avança mais de 70% no acumulado da safra 2026/27, com maior destinação da cana ao biocombustível em detrimento do açúcar.',
  '<p>A moagem de cana-de-açúcar no Centro-Sul do Brasil dobrou na segunda quinzena de abril em comparação ao início da safra, segundo dados da Unica. A produção de etanol avança mais de 70% no acumulado da safra 2026/27.</p><p>A maior destinação da cana ao biocombustível reflete a estratégia das usinas de aproveitar os preços mais atrativos do etanol em relação ao açúcar no período. O ritmo acelerado de moagem indica que a safra 2026/27 pode superar as expectativas iniciais.</p><p>O Brasil é o maior produtor mundial de etanol de cana-de-açúcar e referência global em biocombustíveis. A safra 2026/27 deve consolidar o país como líder no mercado de combustíveis renováveis.</p>',
  'https://images.unsplash.com/photo-1586315776885-a176ffccbe01?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/agricultura/moagem-de-cana-no-centro-sul-dobra-na-2a-quinzena-de-abril-aponta-unica',
  'Biocombustíveis',
  ARRAY['cana-de-açúcar','etanol','Unica','safra','Centro-Sul'],
  '2026-05-29', '2026-05-27', false
),
(
  'governo-avalia-renovar-subvencao-diesel-durigan',
  'Governo avalia renovar subvenção ao diesel na próxima semana',
  'Benefício atual de R$ 0,35 por litro pode ser mantido',
  'O Ministro da Fazenda, Guilherme Durigan, afirmou que o governo está avaliando a renovação da subvenção ao diesel, cujo benefício atual é de R$ 0,35 por litro. A decisão, segundo o ministro, dependerá do comportamento do preço do petróleo nos mercados internacionais e será tomada na semana seguinte ao anúncio.',
  '<p>O Ministro da Fazenda, Guilherme Durigan, afirmou que o governo está avaliando a renovação da subvenção ao diesel, cujo benefício atual é de R$ 0,35 por litro.</p><p>A decisão dependerá do comportamento do preço do petróleo nos mercados internacionais. A subvenção ao diesel tem impacto direto no custo de produção do agronegócio, especialmente para médios e grandes produtores que dependem do combustível para operações de plantio, colheita e transporte.</p><p>O setor agropecuário acompanha de perto a decisão, já que o diesel representa uma das maiores despesas operacionais das fazendas brasileiras. A manutenção da subvenção seria bem recebida pelos produtores rurais.</p>',
  'https://images.unsplash.com/photo-1519003722824-194d4455a60c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/petroleum/13/1137825/governo-avalia-renovar-subvencao-ao-diesel-na-proxima-semana-diz-durigan',
  'Agroeconomia',
  ARRAY['diesel','subvenção','Fazenda','petróleo','custos de produção'],
  '2026-05-29', '2026-05-27', false
),
(
  'alckmin-brasil-retomara-exportacoes-proteinas-ue-setembro',
  'Alckmin afirma que Brasil retomará exportações de proteínas à UE até setembro',
  'País busca comprovar eficiência das medidas sanitárias nas cadeias de carne bovina',
  'O Vice-Presidente Geraldo Alckmin afirmou que o Brasil retomará a habilitação de exportações de proteínas animais para a União Europeia até setembro. O país está buscando comprovar ao bloco europeu a eficiência das medidas de segurança sanitárias nas cadeias produtivas de carne bovina, após restrições impostas pelo bloco.',
  '<p>O Vice-Presidente Geraldo Alckmin afirmou que o Brasil retomará a habilitação de exportações de proteínas animais para a União Europeia até setembro.</p><p>O país está buscando comprovar ao bloco europeu a eficiência das medidas de segurança sanitárias nas cadeias produtivas de carne bovina. A UE é um dos mercados mais exigentes do mundo em termos de protocolos sanitários e rastreabilidade.</p><p>A retomada das exportações para o mercado europeu é considerada estratégica para a diversificação dos destinos da carne bovina brasileira, reduzindo a dependência do mercado chinês e agregando valor ao produto nacional.</p>',
  'https://images.unsplash.com/photo-1559707576-d8806b4a56a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/livestock/5/1137675/alckmin-afirma-que-brasil-retomara-habilitacao-de-exportacoes-de-proteinas-a-ue-ate-setembro',
  'Pecuária',
  ARRAY['carne bovina','União Europeia','exportação','sanidade','Alckmin'],
  '2026-05-29', '2026-05-27', false
),
(
  'receita-industria-maquinas-recua-15-abril-abimaq',
  'Receita da indústria de máquinas recua quase 15% em abril',
  'Setor segue pressionado pela fraqueza do agro e juros elevados',
  'A Abimaq (Associação Brasileira da Indústria de Máquinas e Equipamentos) informou que a receita do setor recuou quase 15% em abril em comparação ao mesmo período do ano anterior. O setor segue pressionado pela fraqueza do agronegócio e pelos juros elevados, apesar da forte alta das exportações de máquinas agrícolas.',
  '<p>A Abimaq informou que a receita do setor recuou quase 15% em abril em comparação ao mesmo período do ano anterior. O setor segue pressionado pela fraqueza do agronegócio e pelos juros elevados.</p><p>Apesar do resultado negativo no mercado interno, as exportações de máquinas agrícolas registraram forte alta, indicando a competitividade do produto brasileiro no exterior. O Brasil é um dos maiores produtores mundiais de máquinas agrícolas.</p><p>A Abimaq aponta que a recuperação do setor depende da melhora das condições de crédito para os produtores rurais e da estabilização das margens no agronegócio, pressionadas pelos altos custos de produção.</p>',
  'https://images.unsplash.com/photo-1585771724684-38269d6639fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/agricultura/receita-da-industria-de-maquinas-recua-quase-15-em-abril-aponta-abimaq',
  'Maquinário',
  ARRAY['máquinas agrícolas','Abimaq','receita','juros','exportação'],
  '2026-05-29', '2026-05-27', false
),
(
  'senado-adia-analise-renegociacao-dividas-rurais',
  'Senado adia análise de projeto sobre renegociação das dívidas rurais',
  'Parlamentares consideram proposta do governo insuficiente',
  'O Senado Federal adiou a análise do projeto de lei que trata da renegociação das dívidas rurais. Parlamentares consideram insuficiente a proposta apresentada pelo governo e defendem uma solução mais ampla para o setor, que envolve passivos com bancos públicos e privados de produtores em dificuldades financeiras.',
  '<p>O Senado Federal adiou a análise do projeto de lei que trata da renegociação das dívidas rurais. Parlamentares consideram insuficiente a proposta apresentada pelo governo e defendem uma solução mais ampla para o setor.</p><p>O debate sobre as dívidas rurais envolve passivos de produtores com bancos públicos (principalmente Banco do Brasil e BNDES) e privados. Estimativas do setor indicam que os débitos totais superam R$ 100 bilhões.</p><p>Representantes do setor agropecuário pressionam por condições mais favoráveis de renegociação, incluindo alongamento dos prazos, redução de juros e mecanismos de proteção para produtores afetados por eventos climáticos adversos.</p>',
  'https://images.unsplash.com/photo-1638403398129-23d6714e8c81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/politica-setorial/senado-adia-analise-de-projeto-sobre-renegociacao-das-dividas-rurais',
  'Política Agrícola',
  ARRAY['dívidas rurais','Senado','crédito rural','renegociação','produtores'],
  '2026-05-29', '2026-05-27', false
),
(
  'ministerio-agricultura-lanca-campanha-organicos',
  'Ministério da Agricultura lança campanha de orgânicos',
  'Iniciativa reforça integração entre governo e redes de produção orgânica',
  'O Ministério da Agricultura lançou uma campanha de valorização e promoção dos alimentos orgânicos. A iniciativa reforça a integração entre o governo e as redes de produção orgânica na implementação de políticas públicas voltadas à sustentabilidade e à alimentação saudável, num momento em que o mercado de orgânicos registra crescimento expressivo no Brasil.',
  '<p>O Ministério da Agricultura lançou uma campanha de valorização e promoção dos alimentos orgânicos. A iniciativa reforça a integração entre o governo e as redes de produção orgânica.</p><p>O mercado de alimentos orgânicos no Brasil cresce em média 20% ao ano e já movimenta mais de R$ 8 bilhões. A campanha busca ampliar o acesso dos consumidores a informações sobre os benefícios dos alimentos orgânicos e fortalecer a cadeia produtiva.</p><p>A produção orgânica é uma importante alternativa para pequenos produtores rurais, que podem obter maior valor agregado por seus produtos e se diferenciar no mercado, tanto no varejo convencional quanto em feiras e plataformas digitais.</p>',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/mais-culturas/15/1137683/ministerio-da-agricultura-lanca-campanha-de-organicos',
  'Outras Culturas',
  ARRAY['orgânicos','sustentabilidade','Ministério da Agricultura','alimentação saudável','produção orgânica'],
  '2026-05-29', '2026-05-27', false
),

-- ── 28/05 ─────────────────────────────────────────────────────────────────────
(
  'camara-aprova-projeto-reformula-seguro-rural',
  'Câmara aprova projeto que reformula seguro rural',
  'Proposta prevê redução nas taxas de juros e fundo bancado com recursos públicos',
  'A Câmara dos Deputados aprovou projeto de lei que reformula o seguro rural no Brasil. A proposta prevê a redução nas taxas de juros para contratação do seguro e a criação de um fundo bancado com recursos públicos para garantir a solvência do sistema. A matéria retorna ao Senado por ter sofrido alterações durante a tramitação na Câmara.',
  '<p>A Câmara dos Deputados aprovou projeto de lei que reformula o seguro rural no Brasil. A proposta prevê a redução nas taxas de juros para contratação do seguro e a criação de um fundo bancado com recursos públicos.</p><p>A reformulação do seguro rural é considerada fundamental para ampliar a proteção dos produtores contra riscos climáticos e de mercado. Atualmente, apenas uma fração dos produtores brasileiros possui seguro rural, e o objetivo é ampliar significativamente essa cobertura.</p><p>A matéria retorna ao Senado por ter sofrido alterações durante a tramitação na Câmara. Representantes do setor agropecuário comemoram a aprovação e pressionam pela aprovação definitiva antes do início do Plano Safra 2026/27.</p>',
  'https://images.unsplash.com/photo-1638403398129-23d6714e8c81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1138436/camara-aprova-projeto-que-reformula-seguro-rural',
  'Política Agrícola',
  ARRAY['seguro rural','Câmara','crédito rural','Plano Safra','legislação'],
  '2026-05-29', '2026-05-28', true
),
(
  'vazio-sanitario-soja-inicia-segunda-feira-sp',
  'Vazio sanitário da soja começa na próxima segunda-feira em SP',
  'Medida tem como objetivo prevenção e controle da ferrugem asiática',
  'O período de vazio sanitário da soja terá início na próxima segunda-feira (1º de junho) no estado de São Paulo. A medida obrigatória tem como objetivo a prevenção e o controle da ferrugem asiática da soja, principal doença fungíca que afeta a cultura no Brasil e pode causar perdas significativas de produtividade.',
  '<p>O período de vazio sanitário da soja terá início na próxima segunda-feira (1º de junho) no estado de São Paulo. A medida obrigatória tem como objetivo a prevenção e o controle da ferrugem asiática da soja.</p><p>Durante o período de vazio sanitário, os produtores devem eliminar plantas voluntárias de soja (tigueras) e restos de cultura das lavouras, além de ser proibida a semeadura da leguminosa. A medida é adotada em todos os estados produtores de soja do Brasil.</p><p>A ferrugem asiática é a principal doença fungíca da soja no Brasil, podendo causar perdas de produtividade de até 80% em casos severos. O manejo adequado durante o vazio sanitário é fundamental para reduzir a pressão do patógeno na safra seguinte.</p>',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/soy/10/1138883/vazio-sanitario-da-soja-comeca-na-proxima-segunda-feira-1o-em-sp',
  'Grãos',
  ARRAY['soja','vazio sanitário','ferrugem asiática','São Paulo','fitossanidade'],
  '2026-05-29', '2026-05-28', true
),
(
  'citricultura-resolucao-criterios-controle-greening-sp',
  'Citricultura: resolução estabelece novos critérios para controle do greening em SP',
  'Medidas visam diminuir a incidência da doença em municípios produtores',
  'Uma nova resolução estabeleceu critérios e procedimentos atualizados para a prevenção e controle do greening (HLB - Huanglongbing) nos citros no estado de São Paulo. As medidas visam diminuir a incidência da doença em municípios onde a atividade citrícola tem impacto econômico relevante.',
  '<p>Uma nova resolução estabeleceu critérios e procedimentos atualizados para a prevenção e controle do greening (HLB) nos citros no estado de São Paulo. As medidas visam diminuir a incidência da doença em municípios produtores.</p><p>O greening é a principal ameaça à citricultura mundial, sem cura conhecida e com capacidade de destruir pomares inteiros. O Brasil, especialmente São Paulo, é o maior produtor e exportador mundial de suco de laranja.</p><p>As novas medidas incluem protocolos reforçados de erradicação de plantas doentes, controle do vetor (psilídeo) e restrições ao trânsito de mudas. A resolução entrou em vigor imediatamente após sua publicação.</p>',
  'https://images.unsplash.com/photo-1547514701-42782101795e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/orange/7/1138576/citricultura-resolucao-estabelece-novos-criterios-e-procedimentos-para-prevencao-e-controle-do-greening-em-sp',
  'Outras Culturas',
  ARRAY['citros','laranja','greening','HLB','São Paulo','fitossanidade'],
  '2026-05-29', '2026-05-28', false
),
(
  'camara-aprova-10-bilhoes-subsidios-fertilizantes',
  'Câmara aprova R$ 10 bilhões em subsídios para novas fábricas de fertilizantes',
  'Texto retorna ao Senado por ter sofrido alterações na Câmara',
  'A Câmara dos Deputados aprovou R$ 10 bilhões em subsídios públicos para incentivar a instalação de novas fábricas de fertilizantes no Brasil. A iniciativa visa reduzir a dependência do país de importações de fertilizantes, que hoje representam mais de 80% do consumo nacional. O texto retorna ao Senado por ter sofrido alterações durante a tramitação.',
  '<p>A Câmara dos Deputados aprovou R$ 10 bilhões em subsídios públicos para incentivar a instalação de novas fábricas de fertilizantes no Brasil.</p><p>A iniciativa visa reduzir a dependência do país de importações de fertilizantes, que hoje representam mais de 80% do consumo nacional. O Brasil é o quarto maior consumidor mundial de fertilizantes.</p><p>A instalação de novas fábricas domésticas de fertilizantes é considerada estratégica para a segurança alimentar e para a redução da vulnerabilidade do agronegócio brasileiro a choques externos, como os provocados pela guerra na Ucrânia em 2022.</p>',
  'https://images.unsplash.com/photo-1516609107823-bf09823c4e4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/fertilizers/16/1138439/camara-aprova-rdollar-10-bilhoes-em-subsidios-para-incentivar-novas-fabricas-de-fertilizantes',
  'Insumos',
  ARRAY['fertilizantes','subsídios','Câmara','indústria','segurança alimentar'],
  '2026-05-29', '2026-05-28', false
),
(
  'agro-fecha-abril-corte-83-mil-vagas-caged',
  'Agro fecha abril com corte de 8,3 mil vagas formais, aponta Caged',
  'Desmobilização nas lavouras de soja e laranja puxou resultado negativo',
  'Segundo o Cadastro Geral de Empregados e Desempregados (Caged), o agronegócio encerrou o mês de abril com saldo negativo de 8,3 mil vagas formais. A desmobilização sazonal nas lavouras de soja (pós-colheita) e nas áreas de laranja foram os principais fatores que puxaram o resultado negativo.',
  '<p>Segundo o Caged, o agronegócio encerrou o mês de abril com saldo negativo de 8,3 mil vagas formais. A desmobilização sazonal nas lavouras de soja e nas áreas de laranja foram os principais fatores que puxaram o resultado negativo.</p><p>O movimento é considerado natural para o período pós-colheita da soja, quando o volume de trabalhadores contratados para o período de colheita é desmobilizado. A expectativa é de recuperação do emprego formal no setor a partir do segundo semestre, com o início das operações de plantio da safra 2026/27.</p><p>No acumulado do ano, o agronegócio ainda apresenta saldo positivo de empregos formais, refletindo a robustez do setor no longo prazo.</p>',
  'https://images.unsplash.com/photo-1585771724684-38269d6639fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/politica-setorial/agro-fecha-abril-com-corte-de-83-mil-vagas-formais-aponta-caged',
  'Agroeconomia',
  ARRAY['emprego','Caged','soja','mercado de trabalho','sazonalidade'],
  '2026-05-29', '2026-05-28', false
),
(
  'setor-fertilizantes-especiais-recua-55-2025',
  'Setor de fertilizantes especiais recua 5,5% em 2025',
  'Segmento encerrou o ano com faturamento de R$ 25,4 bilhões',
  'O setor de fertilizantes especiais (incluindo fertilizantes foliares, organominerais e bioestimulantes) encerrou o ano de 2025 com uma retração de 5,5%, com faturamento de R$ 25,4 bilhões. O resultado reflete o ajuste do setor após anos consecutivos de crescimento acelerado e o movimento dos produtores de redução de custos.',
  '<p>O setor de fertilizantes especiais encerrou o ano de 2025 com uma retração de 5,5%, com faturamento de R$ 25,4 bilhões. O resultado reflete o ajuste do setor após anos consecutivos de crescimento acelerado.</p><p>O movimento de retração está ligado principalmente à redução de custos pelos produtores rurais, que priorizaram insumos básicos em detrimento dos fertilizantes especiais de maior valor agregado num cenário de margens pressionadas.</p><p>Analistas do setor acreditam que a recuperação deve ocorrer a partir de 2026, à medida que os preços das commodities se estabilizem e os produtores retomem os investimentos em produtividade.</p>',
  'https://images.unsplash.com/photo-1624396425072-cddd76f01ddd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/fertilizers/16/1138486/setor-de-fertilizantes-especiais-recua-55-em-2025',
  'Insumos',
  ARRAY['fertilizantes especiais','faturamento','mercado','insumos','agronegócio'],
  '2026-05-29', '2026-05-28', false
),
(
  'pesquisa-24-tomadores-decisao-agro-desconhecem-agricultura-tropical',
  'Pesquisa revela que 24% dos tomadores de decisão do agro desconhecem agricultura tropical',
  'Campanha da CropLife vai abordar especificidades produtivas brasileiras',
  'Uma pesquisa revelou que 24% dos tomadores de decisão do agronegócio brasileiro desconhecem o conceito de agricultura tropical e suas especificidades. Para endereçar essa lacuna, a CropLife Brasil lançou a campanha "O que é que só o Brasil tem?", que busca ampliar a compreensão sobre as soluções e tecnologias desenvolvidas especificamente para as condições dos trópicos.',
  '<p>Uma pesquisa revelou que 24% dos tomadores de decisão do agronegócio brasileiro desconhecem o conceito de agricultura tropical. Para endereçar essa lacuna, a CropLife Brasil lançou a campanha "O que é que só o Brasil tem?".</p><p>A agricultura tropical brasileira é única no mundo: o país produz em solos ácidos de cerrado, num clima quente e úmido, com alta pressão de doenças e pragas. Superar esses desafios exigiu décadas de pesquisa e desenvolvimento de soluções específicas para as condições brasileiras.</p><p>A campanha da CropLife busca valorizar o conhecimento técnico desenvolvido no Brasil e ampliar a compreensão dos tomadores de decisão sobre as especificidades da produção tropical, que permitiram ao país se tornar um dos maiores produtores agrícolas do mundo.</p>',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1138487',
  'Agroeconomia',
  ARRAY['agricultura tropical','CropLife','pesquisa','tecnologia','cerrado'],
  '2026-05-29', '2026-05-28', false
);
