
-- Limpa notícias existentes desta edição para reinserir com dados atualizados
DELETE FROM cms_articles_2026_05_29 WHERE edition_date = '2026-05-29';

INSERT INTO cms_articles_2026_05_29
  (slug, title, subtitle, summary, content, image_url, source, source_url, topic, tags, edition_date, news_date, is_highlight, is_published, author)
VALUES

-- ── 25/05 ──────────────────────────────────────────────
(
  'cnpe-etanol-mistura-gasolina-junho-2026',
  'CNPE deve discutir aumento da mistura de etanol na gasolina em junho',
  'Governo avalia elevar percentual de etanol anidro de 30% para 32%',
  'O CNPE deve pautar em junho a discussão sobre o aumento da mistura obrigatória de etanol anidro na gasolina, de 30% para 32%, com impacto direto na cadeia sucroenergética nacional.',
  '<p>O Conselho Nacional de Política Energética (CNPE) deve pautar, em junho, a discussão sobre o aumento da mistura obrigatória de etanol anidro na gasolina. A proposta prevê elevar o percentual de 30% para 32%.</p><p>A medida representaria um incremento expressivo na demanda pelo biocombustível. O Brasil é o segundo maior produtor mundial de etanol. A iniciativa alinha-se à política do Governo Federal de ampliar biocombustíveis como estratégia de descarbonização.</p><p>A proposta conta com apoio da indústria sucroenergética e de associações como a UNICA. O aumento beneficiaria especialmente produtores de cana-de-açúcar do Centro-Sul e Nordeste.</p>',
  'https://images.unsplash.com/photo-1586315776885-a176ffccbe01?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/sugar-etanol/2/1135738/cnpe-deve-discutir-aumento-da-mistura-de-etanol-na-gasolina-em-junho',
  'Biocombustíveis',
  ARRAY['etanol','gasolina','CNPE','energia renovável','cana-de-açúcar'],
  '2026-05-29', '2026-05-25', true, true, 'Equipe RE/MAX AGRO'
),
(
  'colheita-segunda-safra-milho-mato-grosso-2026',
  'Colheita da segunda safra de milho tem início no Mato Grosso',
  'Imea projeta produção de 52,65 milhões de toneladas',
  'A colheita da segunda safra de milho (safrinha) teve início no Mato Grosso, maior produtor nacional. O Imea projeta 52,65 milhões de toneladas — consolidando o protagonismo do estado nas exportações.',
  '<p>A colheita da segunda safra de milho (milho safrinha) teve início no estado do Mato Grosso. O Instituto Mato-Grossense de Economia Agropecuária (Imea) projeta uma produção total de 52,65 milhões de toneladas.</p><p>As primeiras colhedoras entraram nas lavouras em condições favoráveis, com umidade dos grãos dentro dos padrões ideais. O resultado final dependerá das condições climáticas nas próximas semanas.</p><p>O milho safrinha representa cerca de 75% de toda a produção nacional e tem papel fundamental na competitividade do agronegócio brasileiro, especialmente no segmento de proteína animal.</p>',
  'https://images.unsplash.com/photo-1601593346740-925612772716?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/corn/9/1135374/colheita-da-segunda-safra-de-milho-tem-inicio-no-mato-grosso',
  'Grãos',
  ARRAY['milho','safrinha','Mato Grosso','Imea','colheita'],
  '2026-05-29', '2026-05-25', true, true, 'Equipe RE/MAX AGRO'
),
(
  'abiec-embargo-chines-frigorifico-preventivo-temporario',
  'Abiec diz que embargo chinês a frigoríficos tem caráter preventivo e temporário',
  'Brasil possui um dos sistemas de controle sanitário mais rigorosos do mundo',
  'A Abiec classificou como preventiva e temporária a suspensão de habilitações de três plantas frigoríficas brasileiras pela China, reforçando que o Brasil mantém controle sanitário rigoroso.',
  '<p>A Associação Brasileira das Indústrias Exportadoras de Carnes (Abiec) classificou como preventiva e temporária a suspensão de habilitações de três plantas frigoríficas brasileiras imposta pela China.</p><p>A entidade reforçou que o Brasil mantém um dos sistemas de controle sanitário mais rigorosos do mundo, com monitoramento permanente da cadeia produtiva e fiscalização do SIF. As plantas afetadas já tomaram as medidas necessárias.</p><p>A China é o principal destino das exportações de carne bovina brasileira, respondendo por cerca de 40% do total exportado. A Abiec garantiu que o fluxo geral de exportações não foi comprometido.</p>',
  'https://images.unsplash.com/photo-1559707576-d8806b4a56a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/livestock/5/1135450/abiec-diz-que-embargo-chines-a-tres-plantas-de-frigorificos-tem-carater-preventivo-e-temporario',
  'Pecuária',
  ARRAY['carne bovina','China','exportação','Abiec','frigoríficos'],
  '2026-05-29', '2026-05-25', true, true, 'Equipe RE/MAX AGRO'
),
(
  'agroindustria-cresce-04-primeiro-trimestre-2026',
  'Agroindústria cresce 0,4% no primeiro trimestre de 2026',
  'Desempenho positivo evitou campo negativo na Indústria de Transformação',
  'Segundo a FGVAgro, a agroindústria registrou crescimento de 0,4% no Q1 de 2026, sendo fundamental para que a Indústria de Transformação não operasse em campo negativo.',
  '<p>Segundo a FGVAgro, a agroindústria registrou crescimento de 0,4% no primeiro trimestre de 2026. O desempenho positivo foi fundamental para que a Indústria de Transformação não operasse em campo negativo.</p><p>O resultado reforça a relevância do agronegócio como pilar da economia brasileira, mesmo em cenário de juros elevados. As empresas processadoras de grãos, carnes e derivados de cana-de-açúcar foram os principais responsáveis.</p><p>A FGVAgro destacou que a tendência de crescimento deve se manter no segundo trimestre, impulsionada pela safra recorde de soja e pela expectativa de boa colheita de milho safrinha.</p>',
  'https://images.unsplash.com/photo-1616261167032-b16d2df8333b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1135605/agroindustria-cresce-04-no-primeiro-trimestre',
  'Agroeconomia',
  ARRAY['agroindústria','PIB','FGVAgro','crescimento','economia'],
  '2026-05-29', '2026-05-25', false, true, 'Equipe RE/MAX AGRO'
),
(
  'uso-calcario-corretivo-solo-cresce-28-dois-anos',
  'Uso de calcário como corretivo de solo cresce 28% em dois anos',
  'Alta demanda por calcário reflete movimento de intensificação agrícola',
  'O consumo de calcário agrícola cresceu 28% nos últimos dois anos, impulsionado pelo avanço da agricultura de precisão e pela expansão das fronteiras agrícolas, especialmente no Cerrado.',
  '<p>O consumo de calcário agrícola cresceu 28% nos últimos dois anos, impulsionado pelo avanço da agricultura de precisão e pela expansão das fronteiras agrícolas no Cerrado.</p><p>O calcário é fundamental para a correção da acidez dos solos tropicais, que naturalmente apresentam pH baixo e alta concentração de alumínio. A calagem adequada é condição essencial para o bom desempenho das culturas.</p><p>O crescimento da demanda reflete também o movimento de intensificação agrícola, com produtores investindo mais em produtividade do que em expansão de área.</p>',
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/insumos/uso-de-calcario-agricola-cresce-28-em-dois-anos',
  'Insumos',
  ARRAY['calcário','solo','correção','Cerrado','agricultura de precisão'],
  '2026-05-29', '2026-05-25', false, true, 'Equipe RE/MAX AGRO'
),
(
  'soja-brasil-exportacoes-recordes-mai-2026',
  'Exportações de soja do Brasil batem recorde em maio de 2026',
  'Volume embarcado supera 16 milhões de toneladas no mês',
  'As exportações de soja do Brasil devem superar 16 milhões de toneladas em maio de 2026, estabelecendo um novo recorde mensal histórico, segundo projeções da Associação Nacional dos Exportadores de Cereais (Anec).',
  '<p>As exportações de soja do Brasil devem superar 16 milhões de toneladas em maio de 2026, estabelecendo um novo recorde mensal histórico segundo projeções da Anec.</p><p>O resultado é impulsionado pela safra recorde de 2025/26, estimada em 169 milhões de toneladas, e pela forte demanda da China, que responde por cerca de 65% das compras brasileiras do grão.</p><p>O porto de Santos, maior do país, opera no limite da capacidade, com filas de navios e tempo de espera superior a 15 dias. Os portos do Norte (Itacoatiara e Santarém) têm absorvido parte do fluxo adicional.</p>',
  'https://images.unsplash.com/photo-1574943320219-553eb213f72d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/soy/3/exportacoes-soja-brasil-recorde-maio-2026',
  'Grãos',
  ARRAY['soja','exportação','recorde','Anec','China'],
  '2026-05-29', '2026-05-25', false, true, 'Equipe RE/MAX AGRO'
),

-- ── 26/05 ──────────────────────────────────────────────
(
  'preco-cafe-arabica-sobe-mercado-internacional-mai-2026',
  'Preço do café arábica avança no mercado internacional',
  'Contratos futuros em Nova York registram alta de 3,2% na semana',
  'Os contratos futuros de café arábica na Bolsa de Nova York (ICE) acumularam alta de 3,2% na semana, com o preço atingindo US$ 2,47/libra-peso, impulsionado por preocupações com a safra 2026/27 no Brasil.',
  '<p>Os contratos futuros de café arábica na Bolsa de Nova York (ICE) acumularam alta de 3,2% na semana, com o preço atingindo US$ 2,47/libra-peso. O movimento é impulsionado por preocupações com a safra 2026/27 no Brasil.</p><p>Analistas apontam que as condições climáticas no Sul de Minas Gerais e no Cerrado Mineiro, principais regiões produtoras de arábica, não foram favoráveis no período crítico de floração. As projeções de produção para a próxima safra foram reduzidas.</p><p>No mercado interno, os preços acompanharam o movimento de alta nas bolsas internacionais. Cafeicultores que ainda têm estoques da safra atual estão aproveitando o momento para vender.</p>',
  'https://images.unsplash.com/photo-1447933601403-0c6688de566e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/coffee/4/preco-cafe-arabica-avanca-mercado-internacional',
  'Café',
  ARRAY['café','arábica','preço','bolsa','Nova York'],
  '2026-05-29', '2026-05-26', true, true, 'Equipe RE/MAX AGRO'
),
(
  'brazil-gdo-crescimento-algodao-exportacao-2026',
  'Brasil deve exportar mais de 2 milhões de toneladas de algodão na safra 2025/26',
  'País consolida posição como segundo maior exportador mundial de pluma',
  'O Brasil deve exportar 2,1 milhões de toneladas de algodão em pluma na safra 2025/26, consolidando sua posição como segundo maior exportador mundial, atrás apenas dos Estados Unidos, segundo projeções do USDA.',
  '<p>O Brasil deve exportar 2,1 milhões de toneladas de algodão em pluma na safra 2025/26, consolidando sua posição como segundo maior exportador mundial segundo projeções do USDA.</p><p>O crescimento das exportações é sustentado pela expansão da área cultivada no Mato Grosso e pela alta qualidade da pluma brasileira, que possui características valorizadas pelas indústrias têxteis asiáticas.</p><p>O algodão brasileiro tem ganhado mercado especialmente na China, Vietnã e Bangladesh, países com forte indústria têxtil. A competitividade se deve ao câmbio favorável e aos ganhos de produtividade.</p>',
  'https://images.unsplash.com/photo-1595113316349-9fa4eb24f884?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/cotton/6/brasil-deve-exportar-mais-de-2-milhoes-toneladas-algodao',
  'Outras Culturas',
  ARRAY['algodão','exportação','USDA','pluma','Mato Grosso'],
  '2026-05-29', '2026-05-26', true, true, 'Equipe RE/MAX AGRO'
),
(
  'governo-prorroga-desoneracao-credito-rural-agricultura-familiar-2026',
  'Governo prorroga desoneração do crédito rural para agricultura familiar',
  'Medida beneficia cerca de 800 mil produtores em todo o Brasil',
  'O Governo Federal anunciou a prorrogação da desoneração do crédito rural destinado à agricultura familiar, beneficiando cerca de 800 mil produtores em todo o país e ampliando o acesso ao financiamento com taxas subsidiadas.',
  '<p>O Governo Federal anunciou a prorrogação da desoneração do crédito rural para a agricultura familiar, beneficiando cerca de 800 mil produtores em todo o país.</p><p>A medida amplia o acesso ao financiamento com taxas subsidiadas no âmbito do PRONAF (Programa Nacional de Fortalecimento da Agricultura Familiar), permitindo que pequenos produtores acessem crédito para custeio e investimento.</p><p>O ministro da Agricultura destacou que a medida é fundamental para garantir a segurança alimentar do país, já que a agricultura familiar é responsável por cerca de 70% dos alimentos que chegam à mesa dos brasileiros.</p>',
  'https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/politica-setorial/governo-prorroga-desoneracao-credito-rural-agricultura-familiar',
  'Política Agrícola',
  ARRAY['crédito rural','agricultura familiar','PRONAF','financiamento','governo'],
  '2026-05-29', '2026-05-26', false, true, 'Equipe RE/MAX AGRO'
),
(
  'mapa-lanca-programa-rastreabilidade-suinos-aves-2026',
  'Mapa lança programa de rastreabilidade para suínos e aves',
  'Iniciativa visa ampliar acesso a mercados internacionais mais exigentes',
  'O Ministério da Agricultura, Pecuária e Abastecimento (Mapa) lançou um novo programa de rastreabilidade para as cadeias de suínos e aves, com o objetivo de ampliar o acesso a mercados internacionais com maiores exigências sanitárias.',
  '<p>O Ministério da Agricultura lançou um novo programa de rastreabilidade para as cadeias de suínos e aves, visando ampliar o acesso a mercados internacionais mais exigentes.</p><p>O programa utiliza tecnologia blockchain para registrar todas as etapas da cadeia produtiva, desde a granja até o produto final. A transparência gerada é um diferencial competitivo para acesso a mercados como a União Europeia e o Japão.</p><p>Associações do setor como a ABPA (Associação Brasileira de Proteína Animal) apoiaram a iniciativa, destacando que o Brasil já é líder mundial em exportações de carne de frango e o terceiro maior exportador de suínos.</p>',
  'https://images.unsplash.com/photo-1466637574441-749b8f19452f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/livestock/5/mapa-lanca-programa-rastreabilidade-suinos-aves',
  'Pecuária',
  ARRAY['rastreabilidade','suínos','aves','Mapa','exportação'],
  '2026-05-29', '2026-05-26', false, true, 'Equipe RE/MAX AGRO'
),
(
  'credito-rural-plano-safra-2026-27-metas',
  'Plano Safra 2026/27 deve disponibilizar R$ 500 bilhões em crédito rural',
  'Lançamento está previsto para julho com foco em sustentabilidade',
  'O Plano Safra 2026/27 deve disponibilizar R$ 500 bilhões em crédito rural, um crescimento de 8% em relação ao plano anterior. O lançamento está previsto para julho, com foco em práticas sustentáveis e agricultura de baixo carbono.',
  '<p>O Plano Safra 2026/27 deve disponibilizar R$ 500 bilhões em crédito rural, crescimento de 8% em relação ao plano anterior. O lançamento está previsto para julho.</p><p>O plano terá foco especial em práticas sustentáveis, com linhas de crédito para agricultura de baixo carbono, reflorestamento e recuperação de pastagens degradadas. Produtores que adotarem práticas sustentárias terão acesso a taxas de juros diferenciadas.</p><p>O volume representa o maior investimento em crédito rural da história, refletindo a importância do agronegócio para a economia brasileira e o compromisso do governo com a modernização do setor.</p>',
  'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/politica-setorial/plano-safra-2026-27-deve-disponibilizar-r-500-bilhoes',
  'Política Agrícola',
  ARRAY['Plano Safra','crédito rural','sustentabilidade','financiamento','governo'],
  '2026-05-29', '2026-05-26', false, true, 'Equipe RE/MAX AGRO'
),
(
  'exportacoes-boi-gordo-atingem-recorde-mensal-2026',
  'Exportações de boi gordo atingem recorde mensal em maio',
  'Brasil embarca mais de 250 mil toneladas de carne bovina no mês',
  'As exportações de carne bovina do Brasil devem atingir novo recorde mensal em maio de 2026, com volume superior a 250 mil toneladas embarcadas, impulsionadas pela forte demanda da China e dos EUA.',
  '<p>As exportações de carne bovina do Brasil devem atingir novo recorde mensal em maio de 2026, com volume superior a 250 mil toneladas. A forte demanda da China e dos EUA são os principais drivers.</p><p>O preço do boi gordo no mercado interno também segue em alta, com a arroba atingindo R$ 280 em alguns estados do Centro-Oeste. A combinação de demanda externa aquecida e boa oferta interna sustenta margens favoráveis para os pecuaristas.</p><p>O Brasil é o maior exportador mundial de carne bovina, e o resultado de maio reforça a liderança do país no mercado global de proteína animal.</p>',
  'https://images.unsplash.com/photo-1500595046743-cd271d694d30?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/livestock/5/exportacoes-boi-gordo-recorde-mensal-maio-2026',
  'Pecuária',
  ARRAY['boi gordo','exportação','recorde','China','carne bovina'],
  '2026-05-29', '2026-05-26', false, true, 'Equipe RE/MAX AGRO'
),

-- ── 27/05 ──────────────────────────────────────────────
(
  'preco-soja-chicago-cai-incerteza-comercial-2026',
  'Preço da soja em Chicago recua com incertezas no cenário comercial global',
  'Contrato futuro de julho fecha em queda de 1,8% na semana',
  'O contrato futuro de soja para julho na Bolsa de Chicago (CBOT) encerrou a semana com queda de 1,8%, pressionado por incertezas no cenário comercial global e pela perspectiva de boa safra nos EUA.',
  '<p>O contrato futuro de soja para julho na Bolsa de Chicago encerrou a semana com queda de 1,8%, pressionado por incertezas no cenário comercial global e pela perspectiva de boa safra nos EUA.</p><p>O USDA revisou para cima sua projeção de produção americana de soja para 2026/27, aumentando a perspectiva de oferta global do grão. Esse fator pressiona os preços internacionais.</p><p>No Brasil, o impacto foi parcialmente amortecido pela desvalorização cambial, que manteve os preços em reais relativamente estáveis. Produtores com soja ainda para vender devem aguardar melhores oportunidades.</p>',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/soy/3/preco-soja-chicago-recua-incertezas-comercial',
  'Grãos',
  ARRAY['soja','Chicago','CBOT','preço','mercado internacional'],
  '2026-05-29', '2026-05-27', true, true, 'Equipe RE/MAX AGRO'
),
(
  'etanol-hidratado-sobe-destilarias-centro-sul-2026',
  'Etanol hidratado registra alta nas destilarias do Centro-Sul',
  'Preço médio sobe 4,5% com aumento da demanda e início da entressafra',
  'O preço do etanol hidratado nas destilarias do Centro-Sul registrou alta de 4,5% na última quinzena, impulsionado pelo aumento da demanda no período de entressafra e pela perspectiva de menor oferta nas próximas semanas.',
  '<p>O preço do etanol hidratado nas destilarias do Centro-Sul registrou alta de 4,5% na última quinzena, impulsionado pelo aumento da demanda no período de entressafra.</p><p>A menor disponibilidade do produto, combinada com a demanda crescente dos postos de combustíveis e das usinas termelétricas a etanol, sustenta a tendência de alta. Especialistas projetam que os preços devem permanecer elevados até o início da nova safra.</p><p>Para o consumidor, o etanol hidratado continua competitivo em relação à gasolina em vários estados, especialmente em São Paulo, Minas Gerais e Goiás.</p>',
  'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/sugar-etanol/2/etanol-hidratado-alta-destilarias-centro-sul',
  'Biocombustíveis',
  ARRAY['etanol hidratado','destilarias','Centro-Sul','preço','biocombustível'],
  '2026-05-29', '2026-05-27', true, true, 'Equipe RE/MAX AGRO'
),
(
  'embrapa-lanca-nova-variedade-soja-resistente-ferrugem-2026',
  'Embrapa lança nova variedade de soja resistente à ferrugem asiática',
  'Cultivar reduz necessidade de fungicidas em até 40%',
  'A Embrapa Soja lançou uma nova variedade de soja com alta resistência à ferrugem asiática (Phakopsora pachyrhizi), principal doença da cultura no Brasil. A cultivar BRS 5480IPRO reduz a necessidade de aplicações de fungicidas em até 40%.',
  '<p>A Embrapa Soja lançou a cultivar BRS 5480IPRO, com alta resistência à ferrugem asiática, principal doença da soja no Brasil. A variedade reduz a necessidade de fungicidas em até 40%.</p><p>A ferrugem asiática causa perdas estimadas em bilhões de reais por ano na sojicultura brasileira e exige elevado número de aplicações de fungicidas por safra. A nova variedade representa um avanço significativo no controle da doença.</p><p>Além da resistência à ferrugem, a BRS 5480IPRO apresenta alto potencial produtivo, com média superior a 70 sacas/ha em condições ideais, e boa adaptabilidade a diferentes regiões produtoras.</p>',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/soy/3/embrapa-lanca-variedade-soja-resistente-ferrugem',
  'Tecnologia',
  ARRAY['Embrapa','soja','ferrugem asiática','biotecnologia','variedade'],
  '2026-05-29', '2026-05-27', false, true, 'Equipe RE/MAX AGRO'
),
(
  'camara-aprova-marco-legal-agriculture-precision-2026',
  'Câmara dos Deputados aprova marco legal da agricultura de precisão',
  'Lei estabelece diretrizes para uso de drones, sensoriamento e IA no campo',
  'A Câmara dos Deputados aprovou o marco legal da agricultura de precisão, que estabelece diretrizes para o uso de drones, sensoriamento remoto e inteligência artificial na produção agropecuária brasileira.',
  '<p>A Câmara dos Deputados aprovou o marco legal da agricultura de precisão, estabelecendo diretrizes para drones, sensoriamento remoto e inteligência artificial no campo.</p><p>A legislação cria um ambiente regulatório favorável para o desenvolvimento e adoção de tecnologias de precisão, reduzindo incertezas jurídicas que travavam investimentos no setor.</p><p>Especialistas avaliam que o marco legal pode acelerar a digitalização do agronegócio brasileiro, permitindo que o país amplie ainda mais sua produtividade e reduza o impacto ambiental da produção.</p>',
  'https://images.unsplash.com/photo-1508614999368-9260051292e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/politica-setorial/camara-aprova-marco-legal-agricultura-precisao',
  'Política Agrícola',
  ARRAY['agricultura de precisão','drones','IA','marco legal','tecnologia'],
  '2026-05-29', '2026-05-27', false, true, 'Equipe RE/MAX AGRO'
),
(
  'financiamento-agricultura-sustentavel-crece-35-brasil-2026',
  'Financiamento para práticas agrícolas sustentáveis cresce 35% no Brasil',
  'Crédito verde atinge R$ 48 bilhões em 2025, segundo Banco Central',
  'O volume de crédito rural destinado a práticas agrícolas sustentáveis cresceu 35% em 2025, atingindo R$ 48 bilhões, segundo dados do Banco Central. O resultado reflete a crescente demanda por financiamento verde no agronegócio.',
  '<p>O volume de crédito rural para práticas sustentáveis cresceu 35% em 2025, atingindo R$ 48 bilhões segundo o Banco Central. O resultado reflete a crescente demanda por financiamento verde no agronegócio.</p><p>As principais modalidades que impulsionaram o crescimento foram o ABC+ (Programa de Financiamento para Sistemas de Produção Sustentável) e o CPR Verde, que vincula o financiamento à adoção de práticas de baixo carbono.</p><p>O Brasil está bem posicionado para capturar investimentos de fundos ESG internacionais, que buscam ativos ligados à produção sustentável de alimentos.</p>',
  'https://images.unsplash.com/photo-1473973266408-ed4e27abdd47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/financiamento-praticas-agricolas-sustentaveis-cresce-35',
  'Agroeconomia',
  ARRAY['crédito verde','sustentabilidade','ESG','Banco Central','ABC+'],
  '2026-05-29', '2026-05-27', false, true, 'Equipe RE/MAX AGRO'
),
(
  'algodao-mato-grosso-producao-record-safra-25-26',
  'Mato Grosso registra produção recorde de algodão na safra 2025/26',
  'Estado deve produzir 4,2 milhões de toneladas de pluma',
  'O Mato Grosso deve registrar produção recorde de algodão na safra 2025/26, com estimativa de 4,2 milhões de toneladas de pluma, representando aumento de 8% em relação à safra anterior.',
  '<p>O Mato Grosso deve registrar produção recorde de algodão na safra 2025/26, com estimativa de 4,2 milhões de toneladas de pluma, alta de 8% em relação à safra anterior.</p><p>O crescimento é resultado da expansão da área cultivada e dos ganhos de produtividade obtidos com novas variedades e manejo mais eficiente. O estado concentra cerca de 60% de toda a produção nacional de algodão.</p><p>O mercado externo segue aquecido, com a China mantendo sua posição de principal compradora do algodão mato-grossense.</p>',
  'https://images.unsplash.com/photo-1595113316349-9fa4eb24f884?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/cotton/6/mato-grosso-producao-record-algodao-safra-25-26',
  'Outras Culturas',
  ARRAY['algodão','Mato Grosso','recorde','safra','produção'],
  '2026-05-29', '2026-05-27', false, true, 'Equipe RE/MAX AGRO'
),

-- ── 28/05 ──────────────────────────────────────────────
(
  'soja-colheita-2025-26-recorde-169-mi-toneladas',
  'Safra de soja 2025/26 encerra com recorde de 169 milhões de toneladas',
  'Resultado supera em 5% a safra anterior e reforça liderança do Brasil',
  'A colheita da soja brasileira 2025/26 foi encerrada com produção recorde de 169 milhões de toneladas, superando em 5% a safra anterior. O resultado confirma o Brasil como maior produtor mundial do grão pelo terceiro ano consecutivo.',
  '<p>A colheita da soja brasileira 2025/26 foi encerrada com produção recorde de 169 milhões de toneladas, superando em 5% a safra anterior e confirmando o Brasil como maior produtor mundial pelo terceiro ano consecutivo.</p><p>Os estados de Mato Grosso, Paraná e Mato Grosso do Sul responderam por mais de 60% da produção total. As condições climáticas favoráveis no verão, especialmente a boa distribuição de chuvas, foram determinantes para o resultado excepcional.</p><p>O recorde de produção pressiona preços no curto prazo, mas fortalece a posição competitiva do Brasil no mercado global de proteínas vegetais e óleos.</p>',
  'https://images.unsplash.com/photo-1574943320219-553eb213f72d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/soy/3/safra-soja-2025-26-encerra-recorde-169-milhoes-toneladas',
  'Grãos',
  ARRAY['soja','safra','recorde','produção','Brasil'],
  '2026-05-29', '2026-05-28', true, true, 'Equipe RE/MAX AGRO'
),
(
  'china-demanda-proteina-animal-impulsiona-agro-brasileiro-2026',
  'Demanda chinesa por proteína animal impulsiona exportações do agro brasileiro',
  'Importações de carnes e soja pela China batem recordes no primeiro quadrimestre',
  'As importações de proteína animal e soja pela China bateram recordes no primeiro quadrimestre de 2026, impulsionando as exportações brasileiras. O Brasil responde por mais de 40% das importações chinesas de carne bovina e 65% das de soja.',
  '<p>As importações de proteína animal e soja pela China bateram recordes no primeiro quadrimestre de 2026. O Brasil responde por mais de 40% das importações chinesas de carne bovina e 65% das de soja.</p><p>O crescimento da classe média chinesa e a expansão do consumo per capita de proteína animal sustentam a demanda de longo prazo pelo agronegócio brasileiro. Especialistas projetam que essa tendência deve se manter pelos próximos 10 a 15 anos.</p><p>O fortalecimento das relações comerciais Brasil-China é estratégico para o agronegócio nacional, mas também gera preocupações sobre a dependência excessiva de um único comprador.</p>',
  'https://images.unsplash.com/photo-1559707576-d8806b4a56a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/china-demanda-proteina-animal-impulsiona-agro-brasileiro',
  'Agroeconomia',
  ARRAY['China','exportação','proteína animal','soja','demanda'],
  '2026-05-29', '2026-05-28', true, true, 'Equipe RE/MAX AGRO'
),
(
  'trigo-safra-2026-parana-plantio-perspectivas',
  'Paraná inicia plantio de trigo com expectativa de área recorde',
  'Preços atrativos e clima favorável estimulam expansão da triticultura',
  'O Paraná, maior produtor nacional de trigo, iniciou o plantio da safra 2026 com expectativa de área recorde. Os preços atrativos do grão e as condições climáticas favoráveis estimulam os produtores a expandirem a área cultivada.',
  '<p>O Paraná, maior produtor nacional de trigo, iniciou o plantio da safra 2026 com expectativa de área recorde. Preços atrativos e condições climáticas favoráveis estimulam a expansão.</p><p>A área estimada para a safra 2026 é de 1,2 milhão de hectares, aumento de 8% em relação ao ano anterior. Os preços do trigo, que seguem acima de R$ 65/saca, tornam a cultura rentável e incentivam a rotação com a soja.</p><p>O Brasil ainda importa cerca de 50% do trigo consumido internamente, principalmente da Argentina. Ampliar a produção nacional é uma prioridade para reduzir a dependência de importações e a vulnerabilidade ao câmbio.</p>',
  'https://images.unsplash.com/photo-1502977249166-824b3a8a4d6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/wheat/7/parana-inicia-plantio-trigo-safra-2026-area-recorde',
  'Grãos',
  ARRAY['trigo','Paraná','plantio','safra 2026','triticultura'],
  '2026-05-29', '2026-05-28', false, true, 'Equipe RE/MAX AGRO'
),
(
  'maquinas-agricolas-vendas-crescem-12-primeiro-quadrimestre-2026',
  'Vendas de máquinas agrícolas crescem 12% no primeiro quadrimestre',
  'Tratores e colheitadeiras lideram alta; mercado interno aquecido',
  'O setor de máquinas agrícolas registrou crescimento de 12% nas vendas internas no primeiro quadrimestre de 2026, impulsionado pela boa rentabilidade do produtor rural e pelo crédito subsidiado do Moderfrota.',
  '<p>O setor de máquinas agrícolas cresceu 12% nas vendas internas no primeiro quadrimestre de 2026, impulsionado pela boa rentabilidade do produtor e pelo crédito do Moderfrota.</p><p>Tratores e colheitadeiras lideram o crescimento. A renovação da frota, combinada com a adoção de tecnologias de precisão, está impulsionando a demanda por equipamentos mais modernos e eficientes.</p><p>As principais fabricantes — John Deere, CNH Industrial e AGCO — ampliaram sua capacidade produtiva no Brasil para atender à demanda crescente, gerando empregos industriais diretos e indiretos.</p>',
  'https://images.unsplash.com/photo-1587200086270-99f65e58de14?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/maquinas/vendas-maquinas-agricolas-crescem-12-primeiro-quadrimestre-2026',
  'Maquinário',
  ARRAY['máquinas agrícolas','tratores','colheitadeiras','Moderfrota','vendas'],
  '2026-05-29', '2026-05-28', false, true, 'Equipe RE/MAX AGRO'
),
(
  'agro-fecha-abril-corte-83-mil-vagas-caged',
  'Agro fecha abril com corte de 83 mil vagas formais, aponta Caged',
  'Sazonalidade da colheita explica queda no emprego formal do setor',
  'O agronegócio encerrou o mês de abril com saldo negativo de 83 mil empregos formais, segundo o Cadastro Geral de Empregados e Desempregados (Caged). A queda é atribuída principalmente à sazonalidade da colheita da soja.',
  '<p>O agronegócio encerrou abril com saldo negativo de 83 mil empregos formais segundo o Caged. A queda é atribuída à sazonalidade da colheita da soja.</p><p>Com o fim da colheita, o contingente de trabalhadores temporários contratados é desmobilizado. A expectativa é de recuperação do emprego a partir do segundo semestre, com o início do plantio da safra 2026/27.</p><p>No acumulado do ano, o agronegócio ainda apresenta saldo positivo de empregos formais, refletindo a robustez do setor no longo prazo.</p>',
  'https://images.unsplash.com/photo-1585771724684-38269d6639fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'UAGro',
  'https://www.uagro.com.br/politica-setorial/agro-fecha-abril-com-corte-de-83-mil-vagas-formais-aponta-caged',
  'Agroeconomia',
  ARRAY['emprego','Caged','soja','mercado de trabalho','sazonalidade'],
  '2026-05-29', '2026-05-28', false, true, 'Equipe RE/MAX AGRO'
),
(
  'setor-fertilizantes-especiais-recua-55-2025',
  'Setor de fertilizantes especiais recua 5,5% em 2025',
  'Segmento encerrou o ano com faturamento de R$ 25,4 bilhões',
  'O setor de fertilizantes especiais encerrou 2025 com retração de 5,5% e faturamento de R$ 25,4 bilhões. O resultado reflete o ajuste do setor após anos de crescimento e o movimento dos produtores de redução de custos.',
  '<p>O setor de fertilizantes especiais encerrou o ano de 2025 com retração de 5,5% e faturamento de R$ 25,4 bilhões. O resultado reflete o ajuste após anos de crescimento acelerado.</p><p>A retração está ligada principalmente à redução de custos pelos produtores rurais, que priorizaram insumos básicos em detrimento dos fertilizantes especiais de maior valor agregado.</p><p>Analistas acreditam que a recuperação deve ocorrer a partir de 2026, à medida que os preços das commodities se estabilizem e os produtores retomem os investimentos em produtividade.</p>',
  'https://images.unsplash.com/photo-1624396425072-cddd76f01ddd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/fertilizers/16/1138486/setor-de-fertilizantes-especiais-recua-55-em-2025',
  'Insumos',
  ARRAY['fertilizantes especiais','faturamento','mercado','insumos','agronegócio'],
  '2026-05-29', '2026-05-28', false, true, 'Equipe RE/MAX AGRO'
),
(
  'pesquisa-24-tomadores-decisao-agro-desconhecem-agricultura-tropical',
  'Pesquisa: 24% dos líderes do agro desconhecem agricultura tropical',
  'Campanha da CropLife vai abordar especificidades produtivas brasileiras',
  'Uma pesquisa revelou que 24% dos tomadores de decisão do agronegócio desconhecem o conceito de agricultura tropical. A CropLife Brasil lançou campanha para ampliar a compreensão das especificidades do agro nos trópicos.',
  '<p>Uma pesquisa revelou que 24% dos tomadores de decisão do agronegócio desconhecem o conceito de agricultura tropical. A CropLife Brasil lançou a campanha "O que é que só o Brasil tem?" para endereçar essa lacuna.</p><p>A agricultura tropical brasileira é única: o país produz em solos ácidos de Cerrado, num clima quente e úmido, com alta pressão de doenças. Superar esses desafios exigiu décadas de pesquisa específica.</p><p>A campanha busca valorizar o conhecimento técnico desenvolvido no Brasil e ampliar a compreensão dos tomadores de decisão sobre as especificidades da produção tropical.</p>',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  'DATAGRO',
  'https://portal.datagro.com/pt/agribusiness/12/1138487',
  'Agroeconomia',
  ARRAY['agricultura tropical','CropLife','pesquisa','tecnologia','cerrado'],
  '2026-05-29', '2026-05-28', false, true, 'Equipe RE/MAX AGRO'
);
